### ISSUE TITLE
"make"

### ISSUE THREAD

**Issue by Pyro9224** [klynastor/supervanitygen#11]
sudo apt-get install build-essential automake autoconf libtool libgmp3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-9).
autoconf set to manually installed.
automake is already the newest version (1:1.15-4ubuntu1).
automake set to manually installed.
build-essential is already the newest version (12.1ubuntu2).
libtool is already the newest version (2.4.6-0.1).
libtool set to manually installed.
The following NEW packages will be installed:
  libgmp3-dev
0 upgraded, 1 newly installed, 0 to remove and 141 not upgraded.
Need to get 1,918 B of archives.
After this operation, 21.5 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu xenial/main i386 libgmp3-dev i386 2:6.1.0+dfsg-2 [1,918 B]
Fetched 1,918 B in 0s (10.4 kB/s)
Selecting previously unselected package libgmp3-dev.
(Reading database ... 377181 files and directories currently installed.)
Unpacking libgmp3-dev (2:6.1.0+dfsg-2) .....................................] 

make
make: *** No targets specified and no makefile found.  Stop.

**Comment by klynastor** [comment]
You need to run "make" in the top-level supervanitygen directory that you downloaded.
