### ISSUE TITLE
issues compiling on RHEL7/Centos7

### ISSUE THREAD

**Issue by berniex** [klynastor/supervanitygen#5]
Running make on RHEL7 or Centos 7 systems returns errors because it needs more prerequisites.

This is the complete sequence to successfully compile supervanitygen on el7 from a scratch:

```
yum -y install gcc make automake autoconf libtool gmp-devel unzip
wget https://codeload.github.com/klynastor/supervanitygen/zip/master
unzip ./master
cd ./supervanitygen-master
cd ./secp256k1
cp /usr/share/libtool/config/ltmain.sh ./build-aux/
aclocal
autoconf
autoheader
automake --add-missing
./configure
cd..
./make

```

**Comment by klynastor** [comment]
Thanks for the tips. I'll revise the Readme document shortly.

**Comment by klynastor** [comment]
I added some more information to the README.md that should help. Thanks for the report!
